### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by oneezy** [Zecat/iron-scroll-spy#12] opened 2016-07-15 21:54 UTC
The example appears to be broken still.

Also, my [JS Fiddle](https://jsfiddle.net/oneeezy/c3ertupe/) example has partially quit working as well (animated scrolling to sections).

Any idea what the problem could be?

**Comment by Zecat** [comment] 2016-07-16 21:43
duplicate of #11 ;)
For your fiddle try with the v2 and use `iron-auto-scroll-spy` if you want the auto-scrolling feature, by the way, I forgot to update the readme to explain that!

**Comment by oneezy** [comment] 2016-07-16 22:41
Ahh.., my bad! I'll fiddle around with it

**Closed as completed** 2016-08-26 12:17 UTC
